/**
 * reading.js — render book cards from /books.json
 * books.json is generated by a GitHub Action that fetches Goodreads RSS on a schedule.
 */

(function () {
  const container = document.getElementById('reading-feed');
  if (!container) return;

  function renderCard(book, shelfLabel) {
    const card = document.createElement('div');
    card.className = 'reading-card';

    const coverHtml = book.cover
      ? `<img class="reading-cover" src="${book.cover}" alt="Cover: ${book.title}" loading="lazy" />`
      : `<div class="reading-cover-placeholder"></div>`;

    card.innerHTML = `
      ${coverHtml}
      <div class="reading-info">
        <span class="reading-shelf">${shelfLabel}</span>
        <a class="reading-title" href="${book.link}" target="_blank" rel="noopener">${book.title}</a>
        ${book.author ? `<span class="reading-author">by ${book.author}</span>` : ''}
      </div>
    `;
    return card;
  }

  async function init() {
    try {
      const resp = await fetch('/books.json');
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      const data = await resp.json();

      const current = data.current || [];
      const recent  = data.recent  || [];

      container.innerHTML = '';

      if (current.length === 0 && recent.length === 0) {
        container.innerHTML = '<p class="reading-loading">No books found right now.</p>';
        return;
      }

      current.forEach(book => container.appendChild(renderCard(book, 'Currently reading')));
      recent.forEach(book  => container.appendChild(renderCard(book, 'Recently read')));

    } catch (err) {
      // Fail silently — section stays hidden
      const section = container.closest('#reading');
      if (section) section.style.display = 'none';
    }
  }

  init();
})();
